# Generated by Django 5.1.1 on 2024-09-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nome',
            field=models.CharField(default='', max_length=255, verbose_name='Nome completo:'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação:'),
        ),
    ]
