# Generated by Django 5.1.1 on 2024-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_nome_alter_submission_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
    ]
