# Generated by Django 5.1.1 on 2024-09-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission_comprovante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='arquivo',
            field=models.FileField(upload_to='submissoes/', verbose_name='Arquivo Submetido'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modality', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='thematic_axis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thematicaxis', verbose_name='Eixo Tematico'),
        ),
    ]
