# Generated by Django 5.1.1 on 2024-09-18 17:48

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_submission_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(default='Untitled Submission', max_length=255, verbose_name='Título do Trabalho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='arquivo',
            field=models.FileField(upload_to='submissoes/', validators=[core.models.validate_file_extension], verbose_name='Arquivo Submetido'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='thematic_axis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.thematicaxis', verbose_name='Eixo Temático'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.submission')),
            ],
        ),
    ]
