# Generated by Django 5.1.1 on 2024-09-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submission_title_alter_submission_arquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='acceptance_letter_generated',
            field=models.BooleanField(default=False),
        ),
    ]
