# Generated by Django 5.1.1 on 2024-09-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_submission_arquivo'),
        ('core', '0006_submission_acceptance_letter_generated'),
    ]

    operations = [
    ]
