# Generated by Django 5.1.1 on 2024-09-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20240918_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
